### ISSUE TITLE
Questions in case license server is available separately

### ISSUE THREAD

**Issue by youngung** [Solid-Mechanics/Install-ABAQUS-on-Ubuntu#3]
Where I work, everyone else is using Windows and the license server is already configured for others using Windows.
I'm trying to install Abaqus on a Linux and I am not sure if your 'Install-ABAQUS-on-Ubuntu' works for me.
I know the IP address of the license server so I'm guessing that I do not need to install the license server for myself, is it right?

**Comment by X-G** [comment]
Yes, you don't have to install the license server, instead, you just point your license to `27011@lic_server_ip`.(assuming the license server is on port of 27011 )

**Comment by X-G** [comment]
If you using Abaqus version 6.14.x, I think this tutorial should work.
Recently, Abaqus version 2017 released, It cannot been installed using this tutorial, and its own way of installation is much simpler. 

You can also refer to this tutorial:
https://sites.google.com/site/abaqus2010/help_0
`Install-ABAQUS-on-Ubuntu` is based on it and add fortran configuration.

Let me know if you still have some problem.

**Comment by youngung** [comment]
I was able to run Abaqus on my Ubuntu mainly based on your tutorial but I have an annoying floating window - found the white square in the background of Abaqus window from the attached screenshot.

![Uploading Screen Shot 2017-01-04 at 8.19.08 PM.png…]()

**Comment by X-G** [comment]
I cannot see your screenshot, but I guess I know what you are saying.
You can try to open abaqus/cae, on menu bar toggle: View-Toolbars-Views/Viewport.
The annoying window actually is a toolbar, you can choose to display it or not. Then: Files-save display options-home. Next time when you startup CAE, it will be fine.

Let me know if I'm not talking the case you have.

**Comment by youngung** [comment]
That was it! Thank you!

**Comment by anandkumar89** [comment]
How can I change abaqus GUI font ? 
currently it has very large-bold font. Thanks !

![image](https://cloud.githubusercontent.com/assets/12571250/24237488/8391dcee-0fcc-11e7-96f7-7a2c5c786166.png)
